# Dockerfile per Playwright e test end-to-end
FROM mcr.microsoft.com/playwright:v1.58.2-jammy

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Esegui i test Playwright
CMD ["npx", "playwright", "test"]
